version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: schoolos_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-schoolos}
      POSTGRES_USER: ${POSTGRES_USER:-schoolos}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-schoolos}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-schoolos}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    image: schoolos-backend:latest
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-localhost,backend}
      POSTGRES_HOST: db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    healthcheck:
      test: ['CMD-SHELL', 'curl -fsS http://localhost:8000/healthz || exit 1']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  frontend:
    build:
      context: ./frontend
    image: schoolos-frontend:latest
    depends_on:
      - backend
    environment:
      VITE_API_URL: ${VITE_API_URL:-http://localhost:8000}
    ports:
      - "3000:3000"

volumes:
  db_data:
