name: "✨ Feature Request"
description: "Propose a new capability or enhancement for SchoolOS."
title: "[Feature] <concise summary>"
labels: ["feature", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Summary
        Provide context for the feature or enhancement you are proposing.
  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: "Describe the feature from the perspective of the end user (As a <role>, I want ...)."
      placeholder: "As a Teacher, I want to upload weekly assignments so that students can access them asynchronously."
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: "List measurable conditions that must be satisfied."
      placeholder: "- [ ] Students can upload PDF assignments\n- [ ] Files are scanned for viruses"
    validations:
      required: true
  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: "List other issues, services, or assets that this feature depends on."
      placeholder: "Blocked by Backend API issue #42"
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: "Add design links, metrics, or references."
